services:
  # Bilibili番剧下载器服务
  bili-downloader:
    # 构建上下文为当前目录
    build: .
    # 镜像名称
    image: bili-downloader:alpine
    # 容器名称
    container_name: bili-downloader
    # 工作目录
    working_dir: /app
    # 卷挂载
    volumes:
      # 下载目录挂载
      - ./downloads:/app/downloads
      # Cookie文件挂载到容器根目录（便于读取）
      - ./cookie.txt:/app/cookie.txt:ro
      # 配置目录挂载（用于持久化用户配置）
      # 注意：挂载点必须与Dockerfile中创建的用户家目录一致
      - ./config:/app/config
      # .env文件挂载（用于环境变量配置）
      - ./.env:/app/.env:ro
    # 保持TTY连接
    tty: true
    # 保持stdin打开
    stdin_open: true
    # 重启策略：不自动重启
    restart: no
    # 以下是一些使用示例：
    # 1. 交互式下载（显示帮助信息）：
    # command: ["download", "--help"]
    #
    # 2. 交互式下载（直接开始，需要手动输入参数）：
    # command: ["download"]
    #
    # 3. 自动下载（取消注释并修改URL）：
    # command: ["download", "--url", "YOUR_VIDEO_URL_HERE", "--directory", "/downloads", "--quality", "112", "--downloader", "axel"]
    command: ["download", "--help"] # 默认显示帮助信息