version: '3.8'

services:
  # Bilibili番剧下载器服务
  bili-downloader:
    # 构建上下文为当前目录
    build: .
    # 镜像名称
    image: bili-downloader:latest
    # 容器名称
    container_name: bili-downloader
    # 工作目录
    working_dir: /app
    # 卷挂载
    volumes:
      # 下载目录挂载
      - ./downloads:/downloads
      # Cookie文件挂载到容器根目录（便于读取）
      - ./cookie.txt:/app/cookie.txt:ro
      # 配置目录挂载（用于持久化用户配置）
      - ./config:/home/bilibili/.config/bili-downloader
    # 环境变量配置
    environment:
      # 默认下载器 (axel 或 aria2)
      - DOWNLOAD__DEFAULT_DOWNLOADER=axel
      # 默认下载清晰度
      - DOWNLOAD__DEFAULT_QUALITY=112
      # 默认下载线程数
      - DOWNLOAD__DEFAULT_THREADS=16
      # 合并后是否清理原始文件
      - DOWNLOAD__CLEANUP_AFTER_MERGE=false
      # 请求User-Agent
      - NETWORK__USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
    # 保持TTY连接
    tty: true
    # 保持stdin打开
    stdin_open: true
    # 重启策略：不自动重启
    restart: no
    command: ["download", "--help"]
