[bili-downloader.download]
default_quality = 112
default_downloader = "axel"
default_threads = 16
cleanup_after_merge = false

[bili-downloader.network]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"